export const environment = {
  production: false,
  apiUrl: 'https://taylor-accesscom-production.up.railway.app',
  appName: 'Taylor Access HR',
  version: '1.0.0',
  api: {
    auth: '/api/v1/auth',
    users: '/api/v1/users',
    organizations: '/api/v1/organizations',
    password: '/api/v1/password',
    roles: '/api/v1/roles',
    audit: '/api/v1/audit',
    dashboard: '/api/v1/dashboard',
    twoFactor: '/api/v1/2fa',
    invitations: '/api/v1/invitations',
    bulk: '/api/v1/bulk',
    integrations: '/api/v1/integrations',
    settings: '/api/v1/settings',
    notifications: '/api/v1/notifications',
    drivers: '/api/v1/drivers',
    vehicles: '/api/v1/vehicles',
    contacts: '/api/v1/contacts',
    equipment: '/api/v1/equipment',
    orders: '/api/v1/orders',
    shipments: '/api/v1/shipments',
    loads: '/api/v1/loads',
    documents: '/api/v1/documents',
    invoices: '/api/v1/invoices',
    payables: '/api/v1/payables',
    payments: '/api/v1/payments',
    places: '/api/v1/places',
    fleets: '/api/v1/fleets',
    routes: '/api/v1/routes',
    tracking: '/api/v1/tracking',
    pdf: '/api/v1/pdf',
    geocoder: '/api/v1/geocoder',
    reportBuilder: '/api/v1/reports/builder',
    push: '/api/v1/push',
  }
};
